/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "DropFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DropFactory__factory>;
    getContractFactory(
      name: "DropFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DropFactory__factory>;
    getContractFactory(
      name: "BaseDrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseDrop__factory>;
    getContractFactory(
      name: "IDrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDrop__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "DropFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DropFactory>;
    getContractAt(
      name: "DropFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DropFactory>;
    getContractAt(
      name: "BaseDrop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseDrop>;
    getContractAt(
      name: "IDrop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDrop>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
