/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MerkleDropERC1155FactoryInterface extends ethers.utils.Interface {
  functions: {
    "createDrop(address,address,bytes32,uint256,bytes32,bytes32)": FunctionFragment;
    "predictDropAddress(address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createDrop",
    values: [string, string, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictDropAddress",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "createDrop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictDropAddress",
    data: BytesLike
  ): Result;

  events: {
    "CreateDrop(address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateDrop"): EventFragment;
}

export type CreateDropEvent = TypedEvent<
  [string, string, string] & { drop: string; token: string; ipfsHash: string }
>;

export class MerkleDropERC1155Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MerkleDropERC1155FactoryInterface;

  functions: {
    createDrop(
      template: string,
      token: string,
      merkleRoot: BytesLike,
      expiryTimestamp: BigNumberish,
      salt: BytesLike,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    predictDropAddress(
      implementation: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { predicted: string }>;
  };

  createDrop(
    template: string,
    token: string,
    merkleRoot: BytesLike,
    expiryTimestamp: BigNumberish,
    salt: BytesLike,
    ipfsHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  predictDropAddress(
    implementation: string,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createDrop(
      template: string,
      token: string,
      merkleRoot: BytesLike,
      expiryTimestamp: BigNumberish,
      salt: BytesLike,
      ipfsHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    predictDropAddress(
      implementation: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "CreateDrop(address,address,bytes32)"(
      drop?: string | null,
      token?: string | null,
      ipfsHash?: null
    ): TypedEventFilter<
      [string, string, string],
      { drop: string; token: string; ipfsHash: string }
    >;

    CreateDrop(
      drop?: string | null,
      token?: string | null,
      ipfsHash?: null
    ): TypedEventFilter<
      [string, string, string],
      { drop: string; token: string; ipfsHash: string }
    >;
  };

  estimateGas: {
    createDrop(
      template: string,
      token: string,
      merkleRoot: BytesLike,
      expiryTimestamp: BigNumberish,
      salt: BytesLike,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    predictDropAddress(
      implementation: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createDrop(
      template: string,
      token: string,
      merkleRoot: BytesLike,
      expiryTimestamp: BigNumberish,
      salt: BytesLike,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    predictDropAddress(
      implementation: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
